# Generated by Django 6.0.2 on 2026-02-07 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='')),
                ('description', models.TextField(verbose_name='')),
                ('image', models.ImageField(upload_to='categories/', verbose_name='')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='')),
                ('slug', models.SlugField(max_length=200, verbose_name='')),
                ('image', models.ImageField(blank=True, upload_to='products/', verbose_name='')),
                ('description', models.TextField(blank=True, verbose_name='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='')),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main.category', verbose_name='')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
    ]
